# Generated by Django 2.2.3 on 2020-07-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='phone_number',
            field=models.IntegerField(blank=True, max_length=11, null=True),
        ),
    ]
