# Generated by Django 2.2.3 on 2020-07-28 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200728_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'male'), ('f', 'female')], default='m', max_length=1, null=True, unique=True),
        ),
    ]
