# Generated by Django 2.2.3 on 2020-07-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200728_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
