# Generated by Django 2.2.3 on 2020-01-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_book_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='quote',
            field=models.TextField(blank=True, null=True),
        ),
    ]
