# Generated by Django 2.2.3 on 2020-07-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_author_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='site',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
